steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- bash: |
    pip install -r requirements.txt
    pip install -r requirements_dev.txt
  displayName: Create Python virtual environment

- bash: |
    mypy -p etl --ignore-missing-imports --junit-xml junit/mypy-validation.xml --cache-dir .mypy_cache/
    pycodestyle --ignore=E221,W504,W503 --max-line-length=120 --exclude _*.py --statistics etl
  displayName: Linting

- bash: |
    pytest tests
  displayName: Testing

